---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/11/6 12:22 AM
---

for x = 0, 100, 1 do
    for y = 0, 100, 1 do
        for z = 0, 100, 1 do
            if x + y + z == 100 then
                print(x, y, z)
            end
        end
    end
end