---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/11/23 10:16 AM
---


math.randomseed(os.time())
function rand_number(nStart, nStop)
    return math.random(nStart, nStop)
end

nNum = rand_number(300, 600)
print(nNum)
