---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/12/10 11:50
---
---

package.path = './lib/thinkutils/?.lua;' .. package.path

json = require "lib/json"
thinkutils = require "lib.thinkutils.thinkutils"

print(thinkutils.datetime.timestamp())
print(thinkutils.datetime.today())
print(thinkutils.datetime.now())
print(thinkutils.datetime.diff_day(-3))
print(thinkutils.datetime.hour())
print(thinkutils.datetime.date_2_timestamp("2020-01-01"))
print(thinkutils.datetime.datetime_2_timestamp("2020-01-01 12:13:14"))

print("first day: " .. thinkutils.datetime.firstday_of_month("2020-01-05"))
print("last day: " .. thinkutils.datetime.lastday_of_month("2020-01-31"))

print("first day: " .. thinkutils.datetime.firstday_of_month("2020-12-05"))
print("last day: " .. thinkutils.datetime.lastday_of_month("2020-12-05"))

print("first day: " .. thinkutils.datetime.firstday_of_month("2020-11-15"))
print("last day: " .. thinkutils.datetime.lastday_of_month("2020-11-05"))



print(json.encode(thinkutils.string.split("2020-12-13", "-")))