---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/12/10 11:50
---
---

package.path = './lib/thinkutils/?.lua;' .. package.path

json = require "lib/json"
thinkutils = require "lib.thinkutils.thinkutils"

print(thinkutils.datetime.timestamp())
print(thinkutils.datetime.today())
print(thinkutils.datetime.now())
print(thinkutils.datetime.diff_day(-3))
print(thinkutils.datetime.hour())
print(thinkutils.datetime.date_2_timestamp("2020-01-01"))