---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/11/5 7:21 PM
---
function test()
    print(a, b)
end

function func1()
    a = 1
    do
        b = 2
    end
end

test()
func1()
print(a, b) --1 2
test()



function func2()
    local c = 3
    do
        local d = 4
        do
            local e = 5
            --此处省略100行代码


        end
        print(c, d, e) --3 4 nil
    end

    print(c, d) --3 nil
end
func2()
print(a, b, c, d, e)



area = 0
function rect_area(a, b)
    area = a * b
end

function circle_area(r)
    area = 3.14 * r * r
end

rect_area(2, 3)
circle_area(2)
print("矩形面积: " .. area)
print("圆形面积: " .. area)

