---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/12/10 11:44
---

--package.path = './common/?.lua;' .. package.path
--package.path = package.path .. ';./common/?.lua';

local thinkutils = {}

local datetime = require("common.datetime")
thinkutils.datetime = datetime

return thinkutils
