---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/11/28 14:26
---

function isprime(nNum)
    if 1 == nNum then
        return false
    end

    if 2 == nNum then
        return true
    end

    if 0 == nNum % 2 then
        return false
    end

    for x = 2, nNum / 2, 1 do
        if nNum % x == 0 then
            return false
        else

        end
    end

    return true
end

function goldbach(nNum)
    for i = 3, nNum - 1, 2 do
        local a = i
        local b = nNum - i
        if isprime(a) and isprime(b) then
            print(string.format("%d = %d + %d", nNum, a, b))
        end
    end
end
goldbach(200)