---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/12/31 18:18
---

package.path = './lib/thinkutils/?.lua;' .. package.path
local thinkutils = require "lib.thinkutils.thinkutils"

local lstCsv = thinkutils.common.csvutils.csv_2_dictlist("jd_2020-12-29.csv")
print(#lstCsv)
