---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by BBQ.
--- DateTime: 2020/11/20 17:44
---
--1.( ( (王老师年龄+1) *3) /2+40)/4-25=0 王老师多大
--function age()
--    for i = 1, 100 do
--        if ( ( (i+1) *3) /2+40)/4-25 == 0 then
--            return i
--        end
--    end
--end
--print(age())


--2.甲乙和为168，甲1/8与乙2/3和为76，求甲乙各多少
for x = 1, 168 do
    for y = 1, 168 do
        if x + y == 168
        if x + y == 168 then
            else
            if x/8 + 2*y/3 == 76 then
                print(x, y)
            end
        end
    end
end


--3.跨台阶 每步跨二剩一，跨三剩二，五剩四，六剩五，七正好，问有几阶梯---------------------------------------
--x%2-1==0
--x%3-2==0
--x%5-4==0
--x%6-5==0
--x%7==0
--while   do
--
--end


--4.把一元分成一分 两分 五分 （每种至少一枚） 有几种换法
--for x = 1, 98 do
--    for y = 1, 48 do
--        for z = 1, 18 do
--            if 98*x+48*y+18*z == 100 then
--                print(x,y,z)
--            end
--        end
--    end
--end


--5.100匹马 100担货 大马驮3担 中马驮2担 两个小马驮1担 有几个方法 大马中马各几匹 列出组合
--for x = 1, 98 do
--    for y = 1, 98 do
--        for z = 1, 98 do
--            if x + y + z == 100 then
--                if 3*x+2*y+z/2 == 100 then
--                    print(x, y, z)
--                end
--            end
--        end
--    end
--end


--6.公鸡5元/只 母鸡3元/只 小鸡三只一元  用100元买100只鸡 三只鸡各有一只 几种方法
--array = { }
--for x = 1, 98 do
--    for y = 1, 98 do
--        for z = 1, 98 do
--            if x + y + z == 100 then
--                if 5*x+3*y+z/3 == 100 then
--                    print(x, y, z)
--                end
--            end
--        end
--    end
--end


--7.有个三位数 个位数比百位数大 百位数比十位数大 各数字之和等于各数字乘积，求这三位数
--for x = 1, 9 do
--    for y = 1, 9 do
--        for z = 1, 9 do
--            if x + y + z == x*y*z then
--                    print(x, y, z)
--            end
--        end
--    end
--end


--8.汽车载客50人 一部分人买成人票8元/张 一部分人买儿童票3元/张 成人票比儿童票多收入180 成人票儿童票各多少人
--for x = 1, 50 do
--    for y = 1, 50 do
--        if x + y == 50 then
--            if 8*x-3*y == 180 then
--                print(x, y)
--            end
--        end
--    end
--end


--9.打印出所有水仙花数，  如 153=1^3+5^3+3^3
--for x = 0, 9 do
--    for y = 0, 9 do
--        for z = 0, 9 do
--            if x^3+y^3+z^3 == 100*x+10*y+z then
--                    print(x, y, z)
--            end
--        end
--    end
--end


--10.二元一次方程：a,b都是正整数 已知求a,b：--a+2b=4--3a+2b=8
--a+2*b == 4
--3*a+2*b == 8






