---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/12/10 18:42
---

package.path = './?.lua;' .. package.path
local stringutils = require("common.stringutils")

local csvutils = {}

csvutils.csv_2_dict_list = function (szFilePath)
    local nLine = 0
    local lstHeader = {}
    local lstRet = {}

    for szLine in io.lines(szFilePath) do
        nLine = nLine + 1

        if 1 == nLine then
            local lstTemp = stringutils.split(szLine, ",")
            for i = 1, #lstTemp do
                table.insert(lstHeader, stringutils.trim(lstTemp[i]))
            end
        else
            local dictItem = {}

            local lstTemp = stringutils.split(szLine, ",")
            for i = 1, #lstTemp do
                dictItem[lstHeader[i]] = stringutils.trim(lstTemp[i])
            end

            table.insert(lstRet, dictItem)
        end

    end

    return lstRet
end

return csvutils