---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/11/24 00:04
---

function init_gold(nDay)
    lstGold = {}
    for i = 1, nDay do
        --if i == nDay then
        --    table.insert(lstGold, nDay)
        --else
            table.insert(lstGold, 0)
        --end
    end
end

function gold_number(nDate, nMax)
    nSum = 0
    for nDay = nDate, nMax do
        if nDay == nMax then
            nSum = nSum + nDay
        else
            nSum = nSum +  nDay + gold_number(nDay + 1, nMax) / 7
        end
    end

    return nSum
end

print(gold_number(3))